// class-41/demo/angular-todos/src/todo-form/todo-form.component.ts
import { Component, Output, EventEmitter } from '@angular/core';

@Component({
  selector: 'todo-form',
  template:`
    <form (ngSubmit)="onSubmit()">
      <input [(ngModel)]="newTodo.text" name="text" type="text">
      <input [(ngModel)]="newTodo.assignee" name="assignee" type="text">
      <button type="submit">Add Todo</button>
    </form>
  `
})
export class TodoFormComponent {
  newTodo: { text: string, assignee: string} = { text: '', assignee: ''}

  @Output() addTodoEvent = new EventEmitter<{ text: string, assignee: string}>()

  onSubmit() {
    this.addTodoEvent.emit(this.newTodo);
    this.newTodo = {text: '', assignee: ''};
  }
}

// class-41/demo/vue-todos/src/components/TodoForm.vue
<script setup>
import {ref, defineEmits} from 'vue';

const emit = defineEmits(['addTodo']);
let newTodo = ref({
  text: '',
  assignee: ''
});

const handleSubmit = (todo) => {
  emit('addTodo', todo);
  newTodo.value = { text: '', assignee: ''}
}
</script>

<template>
  <form @submit.prevent="handleSubmit(newTodo)">
    <input type="text" id="todoText" v-model="newTodo.text" />
    <input type="text" id="todoAssignee" v-model="newTodo.assignee" />
    <button type="submit">Add Todo</button>
  </form>
</template>
