// class-41/demo/vue-todos/src/components/TodoList.vue
<script setup>
  defineProps({
    todos: {
      type: Array,
      required: true
    }
  })
</script>

<template>
  <div>
    <h2>Todo List</h2>
    <ul>
      <li v-for="todo in todos">
        <strong>{{ todo.text }}</strong> - Assigned to {{ todo.assignee }}
      </li>
    </ul>
  </div>
</template>

// class-41/demo/angular-todos/src/todo-list/todo-list.component.ts
import { Component, Input } from '@angular/core'

@Component({
  selector: 'todo-list',
  template: `
    <div>
      <h2>Todo List</h2>
      <ul>
        <li *ngFor="let todo of todos">
          <strong>{{ todo.text }}</strong> - Assigned to {{ todo.assignee }}
        </li>
      </ul>
    </div>
  `
})
export class TodoListComponent {
  @Input() todos!: Array<{ text: string; assignee: string }>;
}
